export const manufacturers = [
    'Acura',
    'Alfa Romeo',
    'Aston Martin',
    'Audi',
    'Bentley',
    'BMW',
    'Buick',
    'Cadillac',
    'Chevrolet',
    'Chrysler',
    'Citroen',
    'Dodge',
    'Ferrari',
    'Fiat',
    'Ford',
    'GMC',
    'Honda',
    'Hyundai',
    'Infiniti',
    'Jaguar',
    'Jeep',
    'Kia',
    'Lamborghini',
    'Land Rover',
    'Lexus',
    'Lincoln',
    'Maserati',
    'Mazda',
    'McLaren',
    'Mercedes-Benz',
    'MINI',
    'Mitsubishi',
    'Nissan',
    'Porsche',
    'Ram',
    'Rolls-Royce',
    'Subaru',
    'Tesla',
    'Toyota',
    'Volkswagen',
    'Volvo',
];
  
export const yearsOfProduction: FilterOption[] = [
    { title: 'Year', value: '' },
    { title: '2015', value: '2015' },
    { title: '2016', value: '2016' },
    { title: '2017', value: '2017' },
    { title: '2018', value: '2018' },
    { title: '2019', value: '2019' },
    { title: '2020', value: '2020' },
    { title: '2021', value: '2021' },
    { title: '2022', value: '2022' },
    { title: '2023', value: '2023' },
    { title: '2024', value: '2024' },
];
  
export const fuels: FilterOption[]  = [
    {
        title: 'Fuel',
        value: '',
    },

    {
        title: 'Gas',
        value: 'Gas',
    },
    {
        title: 'Electricity',
        value: 'Electricity',
    },
];
  
export const footerLinks = [
    {
        title: 'About',
        links: [
            { name: 'How it works', url: '/' },
            { name: 'Featured', url: '/' },
            { name: 'Partnership', url: '/' },
            { name: 'Bussiness', url: '/' },
        ],
    },
    {
        title: 'Company',
        links: [
            { name: 'Events', url: '/' },
            { name: 'Blog', url: '/' },
            { name: 'Podcast', url: '/' },
            { name: 'Invite a friend', url: '/' },
        ],
    },
    {
        title: 'Socials',
        links: [
            { name: 'Discord', url: '/' },
            { name: 'Instagram', url: '/' },
            { name: 'Twitter', url: '/' },
            { name: 'Facebook', url: '/' },
        ],
    },
];

export const dummy = [
    {
        'city_mpg': 23,
        'class': 'compact car',
        'combination_mpg': 24,
        'cylinders': 4,
        'displacement': 1.6,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 26,
        'make': 'toyota',
        'model': 'corolla',
        'transmission': 'a',
        'year': 1999
    },
    {
        'city_mpg': 23,
        'class': 'compact car',
        'combination_mpg': 26,
        'cylinders': 4,
        'displacement': 1.6,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 31,
        'make': 'toyota',
        'model': 'corolla',
        'transmission': 'm',
        'year': 2007
    },
    {
        'city_mpg': 23,
        'class': 'compact car',
        'combination_mpg': 25,
        'cylinders': 4,
        'displacement': 1.8,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 30,
        'make': 'toyota',
        'model': 'corolla',
        'transmission': 'a',
        'year': 2014
    },
    {
        'city_mpg': 23,
        'class': 'compact car',
        'combination_mpg': 26,
        'cylinders': 4,
        'displacement': 1.8,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 30,
        'make': 'toyota',
        'model': 'corolla',
        'transmission': 'm',
        'year': 1995
    },
    {
        'city_mpg': 23,
        'class': 'small station wagon',
        'combination_mpg': 25,
        'cylinders': 4,
        'displacement': 1.8,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 30,
        'make': 'toyota',
        'model': 'corolla wagon',
        'transmission': 'a',
        'year': 2009
    },
    {
        'city_mpg': 23,
        'class': 'compact car',
        'combination_mpg': 24,
        'cylinders': 4,
        'displacement': 1.6,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 26,
        'make': 'toyota',
        'model': 'corolla',
        'transmission': 'a',
        'year': 2023
    },
    {
        'city_mpg': 22,
        'class': 'compact car',
        'combination_mpg': 23,
        'cylinders': 4,
        'displacement': 2.0,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 25,
        'make': 'honda',
        'model': 'civic',
        'transmission': 'm',
        'year': 2018
    },
    {
        'city_mpg': 20,
        'class': 'midsize car',
        'combination_mpg': 22,
        'cylinders': 6,
        'displacement': 2.5,
        'drive': 'awd',
        'fuel_type': 'gas',
        'highway_mpg': 24,
        'make': 'subaru',
        'model': 'outback',
        'transmission': 'a',
        'year': 2003
    },
    {
        'city_mpg': 18,
        'class': 'full-size car',
        'combination_mpg': 20,
        'cylinders': 8,
        'displacement': 4.0,
        'drive': 'rwd',
        'fuel_type': 'gas',
        'highway_mpg': 22,
        'make': 'chevrolet',
        'model': 'impala',
        'transmission': 'a',
        'year': 2011
    },
    {
        'city_mpg': 25,
        'class': 'compact car',
        'combination_mpg': 27,
        'cylinders': 4,
        'displacement': 1.8,
        'drive': 'fwd',
        'fuel_type': 'hybrid',
        'highway_mpg': 30,
        'make': 'toyota',
        'model': 'prius',
        'transmission': 'cvt',
        'year': 2012
    },
    {
        'city_mpg': 21,
        'class': 'midsize car',
        'combination_mpg': 23,
        'cylinders': 6,
        'displacement': 3.0,
        'drive': 'awd',
        'fuel_type': 'diesel',
        'highway_mpg': 25,
        'make': 'audi',
        'model': 'a6',
        'transmission': 'a',
        'year': 2018
    },
    {
        'city_mpg': 21,
        'class': 'midsize car',
        'combination_mpg': 23,
        'cylinders': 6,
        'displacement': 3.0,
        'drive': 'awd',
        'fuel_type': 'diesel',
        'highway_mpg': 25,
        'make': 'audi',
        'model': 'a6',
        'transmission': 'a',
        'year': 2018
    },
    {
        'city_mpg': 19,
        'class': 'full-size car',
        'combination_mpg': 21,
        'cylinders': 8,
        'displacement': 5.0,
        'drive': 'rwd',
        'fuel_type': 'gas',
        'highway_mpg': 22,
        'make': 'ford',
        'model': 'mustang',
        'transmission': 'm',
        'year': 2013
    },
    {
        'city_mpg': 24,
        'class': 'compact car',
        'combination_mpg': 26,
        'cylinders': 4,
        'displacement': 1.8,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 28,
        'make': 'honda',
        'model': 'accord',
        'transmission': 'cvt',
        'year': 2017
    },
    {
        'city_mpg': 17,
        'class': 'midsize car',
        'combination_mpg': 19,
        'cylinders': 6,
        'displacement': 3.5,
        'drive': 'fwd',
        'fuel_type': 'hybrid',
        'highway_mpg': 21,
        'make': 'toyota',
        'model': 'camry',
        'transmission': 'a',
        'year': 2016
    },
    {
        'city_mpg': 27,
        'class': 'compact car',
        'combination_mpg': 29,
        'cylinders': 4,
        'displacement': 1.5,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 31,
        'make': 'hyundai',
        'model': 'elantra',
        'transmission': 'a',
        'year': 2022
    },
    {
        'city_mpg': 17,
        'class': 'midsize car',
        'combination_mpg': 19,
        'cylinders': 6,
        'displacement': 3.5,
        'drive': 'fwd',
        'fuel_type': 'hybrid',
        'highway_mpg': 21,
        'make': 'toyota',
        'model': 'camry',
        'transmission': 'a',
        'year': 2016
    },
    {
        'city_mpg': 27,
        'class': 'compact car',
        'combination_mpg': 29,
        'cylinders': 4,
        'displacement': 1.5,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 31,
        'make': 'hyundai',
        'model': 'elantra',
        'transmission': 'a',
        'year': 2022
    },
    {
        'city_mpg': 17,
        'class': 'midsize car',
        'combination_mpg': 19,
        'cylinders': 6,
        'displacement': 3.5,
        'drive': 'fwd',
        'fuel_type': 'hybrid',
        'highway_mpg': 21,
        'make': 'toyota',
        'model': 'camry',
        'transmission': 'a',
        'year': 2016
    },
    {
        'city_mpg': 27,
        'class': 'compact car',
        'combination_mpg': 29,
        'cylinders': 4,
        'displacement': 1.5,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 31,
        'make': 'hyundai',
        'model': 'elantra',
        'transmission': 'a',
        'year': 2022
    },
    {
        'city_mpg': 23,
        'class': 'compact car',
        'combination_mpg': 24,
        'cylinders': 4,
        'displacement': 1.6,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 26,
        'make': 'toyota',
        'model': 'corolla',
        'transmission': 'a',
        'year': 1999
    },
    {
        'city_mpg': 23,
        'class': 'compact car',
        'combination_mpg': 26,
        'cylinders': 4,
        'displacement': 1.6,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 31,
        'make': 'toyota',
        'model': 'corolla',
        'transmission': 'm',
        'year': 2007
    },
    {
        'city_mpg': 23,
        'class': 'compact car',
        'combination_mpg': 25,
        'cylinders': 4,
        'displacement': 1.8,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 30,
        'make': 'toyota',
        'model': 'corolla',
        'transmission': 'a',
        'year': 2014
    },
    {
        'city_mpg': 23,
        'class': 'compact car',
        'combination_mpg': 26,
        'cylinders': 4,
        'displacement': 1.8,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 30,
        'make': 'toyota',
        'model': 'corolla',
        'transmission': 'm',
        'year': 1995
    },
    {
        'city_mpg': 23,
        'class': 'small station wagon',
        'combination_mpg': 25,
        'cylinders': 4,
        'displacement': 1.8,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 30,
        'make': 'toyota',
        'model': 'corolla wagon',
        'transmission': 'a',
        'year': 2009
    },
    {
        'city_mpg': 23,
        'class': 'compact car',
        'combination_mpg': 24,
        'cylinders': 4,
        'displacement': 1.6,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 26,
        'make': 'toyota',
        'model': 'corolla',
        'transmission': 'a',
        'year': 2023
    },
    {
        'city_mpg': 22,
        'class': 'compact car',
        'combination_mpg': 23,
        'cylinders': 4,
        'displacement': 2.0,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 25,
        'make': 'honda',
        'model': 'civic',
        'transmission': 'm',
        'year': 2018
    },
    {
        'city_mpg': 20,
        'class': 'midsize car',
        'combination_mpg': 22,
        'cylinders': 6,
        'displacement': 2.5,
        'drive': 'awd',
        'fuel_type': 'gas',
        'highway_mpg': 24,
        'make': 'subaru',
        'model': 'outback',
        'transmission': 'a',
        'year': 2003
    },
    {
        'city_mpg': 18,
        'class': 'full-size car',
        'combination_mpg': 20,
        'cylinders': 8,
        'displacement': 4.0,
        'drive': 'rwd',
        'fuel_type': 'gas',
        'highway_mpg': 22,
        'make': 'chevrolet',
        'model': 'impala',
        'transmission': 'a',
        'year': 2011
    },
    {
        'city_mpg': 25,
        'class': 'compact car',
        'combination_mpg': 27,
        'cylinders': 4,
        'displacement': 1.8,
        'drive': 'fwd',
        'fuel_type': 'hybrid',
        'highway_mpg': 30,
        'make': 'toyota',
        'model': 'prius',
        'transmission': 'cvt',
        'year': 2012
    },
    {
        'city_mpg': 21,
        'class': 'midsize car',
        'combination_mpg': 23,
        'cylinders': 6,
        'displacement': 3.0,
        'drive': 'awd',
        'fuel_type': 'diesel',
        'highway_mpg': 25,
        'make': 'audi',
        'model': 'a6',
        'transmission': 'a',
        'year': 2018
    },
    {
        'city_mpg': 21,
        'class': 'midsize car',
        'combination_mpg': 23,
        'cylinders': 6,
        'displacement': 3.0,
        'drive': 'awd',
        'fuel_type': 'diesel',
        'highway_mpg': 25,
        'make': 'audi',
        'model': 'a6',
        'transmission': 'a',
        'year': 2018
    },
    {
        'city_mpg': 19,
        'class': 'full-size car',
        'combination_mpg': 21,
        'cylinders': 8,
        'displacement': 5.0,
        'drive': 'rwd',
        'fuel_type': 'gas',
        'highway_mpg': 22,
        'make': 'ford',
        'model': 'mustang',
        'transmission': 'm',
        'year': 2013
    },
    {
        'city_mpg': 24,
        'class': 'compact car',
        'combination_mpg': 26,
        'cylinders': 4,
        'displacement': 1.8,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 28,
        'make': 'honda',
        'model': 'accord',
        'transmission': 'cvt',
        'year': 2017
    },
    {
        'city_mpg': 17,
        'class': 'midsize car',
        'combination_mpg': 19,
        'cylinders': 6,
        'displacement': 3.5,
        'drive': 'fwd',
        'fuel_type': 'hybrid',
        'highway_mpg': 21,
        'make': 'toyota',
        'model': 'camry',
        'transmission': 'a',
        'year': 2016
    },
    {
        'city_mpg': 27,
        'class': 'compact car',
        'combination_mpg': 29,
        'cylinders': 4,
        'displacement': 1.5,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 31,
        'make': 'hyundai',
        'model': 'elantra',
        'transmission': 'a',
        'year': 2022
    },
    {
        'city_mpg': 17,
        'class': 'midsize car',
        'combination_mpg': 19,
        'cylinders': 6,
        'displacement': 3.5,
        'drive': 'fwd',
        'fuel_type': 'hybrid',
        'highway_mpg': 21,
        'make': 'toyota',
        'model': 'camry',
        'transmission': 'a',
        'year': 2016
    },
    {
        'city_mpg': 27,
        'class': 'compact car',
        'combination_mpg': 29,
        'cylinders': 4,
        'displacement': 1.5,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 31,
        'make': 'hyundai',
        'model': 'elantra',
        'transmission': 'a',
        'year': 2022
    },
    {
        'city_mpg': 17,
        'class': 'midsize car',
        'combination_mpg': 19,
        'cylinders': 6,
        'displacement': 3.5,
        'drive': 'fwd',
        'fuel_type': 'hybrid',
        'highway_mpg': 21,
        'make': 'toyota',
        'model': 'camry',
        'transmission': 'a',
        'year': 2016
    },
    {
        'city_mpg': 27,
        'class': 'compact car',
        'combination_mpg': 29,
        'cylinders': 4,
        'displacement': 1.5,
        'drive': 'fwd',
        'fuel_type': 'gas',
        'highway_mpg': 31,
        'make': 'hyundai',
        'model': 'elantra',
        'transmission': 'a',
        'year': 2022
    }
];