import type { Metadata, NextPage } from 'next';
import type { PropsWithChildren } from 'react';
import { Inter } from 'next/font/google'
import Footer from '@/components/feature/root/Footer';
import Header from '@/components/feature/root/Header';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: NextPage<PropsWithChildren> = ({ children }) => {

    return (
        <html lang='en'>
            <body className={inter.className}>
                <div className='text-white bg-gradient-to-br from-black to-zinc-600'>
                    <div className='flex flex-col max-w-screen-xl mx-auto min-h-dvh'>
                        <Header />
                        <main className='flex-1 px-4 md:px-7 lg:px-10'>
                            {children}
                        </main>
                        <Footer />
                    </div>                
                </div>
            </body>
        </html>
    );  
}

export default RootLayout;